### ISSUE TITLE
[Question] is it possible for you to add dynamic shadows and will you make a discord server and what happened to you previous website?

### ISSUE THREAD

**Issue by Darthveder69420** [Mcbamboo/bicubic-shaders-be#10]

**Comment by bambosan** [comment]
for discord, it seems like I can't make it because I can't focus on taking care of it
for website, I'm redesigning but I'm too lazy to finish it

**Comment by Darthveder69420** [comment]
And what about dynamic shadows? Is it possible? It would make the shader perfect.
