### ISSUE TITLE
I don't know what is this

### ISSUE THREAD

**Issue by MEEMAPLAY** [Mcbamboo/bicubic-shaders-be#2]
![image](https://user-images.githubusercontent.com/83797362/117461433-beae6000-af77-11eb-8e22-67f0ce2f8503.png)

**Comment by bambosan** [comment]
where are you (Minecraft)
overworld or something?

**Comment by MEEMAPLAY** [comment]
It happened on the surface of the water.

**Comment by bambosan** [comment]
it was a bug of normal map precision and I fixed it
