### ISSUE TITLE
Invisible world when using latest Bicubic dev 

### ISSUE THREAD

**Issue by ghost** [Mcbamboo/bicubic-shaders-be#20]
In case you needed:
Mcpe 1.17.2
iPhone 7+ (chip A10)
Latest Bicubic dev
I downloaded the updated Bicubic dev to see if the water flow texture has been fixed, but when I create and a new word, it’s completely invisible and only the sky and cloud work

**Comment by Darthveder69420** [comment]
1.17 is not compatible!

**Comment by Darthveder69420** [comment]
!close

**Comment by ghost** [comment]
> 1.17 is not compatible!

Idk but to me, some shaders is still working include this shader. The only thing that 1.17 breaks the shader is the underwater wave, underwater fog and underwater caustic

**Comment by Darthveder69420** [comment]
He needs to update it so it would work. The other shaders are probably have been updated.
