### ISSUE TITLE
About Win10 edition V1.17

### ISSUE THREAD

**Issue by xzajyjs** [Mcbamboo/bicubic-shaders-be#21]
Though the 3.0 beta cannot work well on win10 v1.17.2 edition.This shader is so great that I use it both on my ipad and my iphone.Now i want to use it on win10 edition 1.17.Hope you can update it !

**Comment by shizotoaster** [comment]
Well, you can't use any shader on win10 rn, it's not dev's fault

**Comment by paula867** [comment]
> Though the 3.0 beta cannot work well on win10 v1.17.2 edition.This shader is so great that I use it both on my ipad and my iphone.Now i want to use it on win10 edition 1.17.Hope you can update it !

Can you pleeeease tell me how i can get this shader on my iPad? I tried the v3.0 .mcpack but the whole world aside from the sky was invisible. I then tried to change the file to .zip but the textures where messed up and the shader only partially worked, the unzipped version is not invisible but it's unplayable. 

I'm very frustrated I tried everything i know, i tried installing other shaders but they all had the same invisibility issue. i don't know what I'm doing wrong.
