### ISSUE TITLE
Issues with Intel GPU

### ISSUE THREAD

**Issue by shizotoaster** [Mcbamboo/bicubic-shaders-be#22]
Game version: 1.17.2 release
Bicubic version: 3.1-dev
GPU: Intel HD graphics 520
Resolution: Regular/no clouds
Result: 
![image](https://user-images.githubusercontent.com/51480483/124364653-14983f00-dc6d-11eb-9df6-bca66167f675.png)

**Comment by SteveAlexM** [comment]
are you using bicubic shaders version 3.1 dev?  if so, just ask me again what the problem is, because I am the creator of this 3.1 dev release.

**Comment by shizotoaster** [comment]
Yes, I was using 3.1 dev. I've tried it on both 1.16 and 1.17 and blocks just does not render. It's probably because of my GPU is unsupported rn. I think, it is caused by waterbump because everything works fine when it's turned off

**Comment by SteveAlexM** [comment]
Yes, thank you for the report, I will fix the shaders later
