### ISSUE TITLE
small lines on the screen (on iOS)

### ISSUE THREAD

**Issue by bedrockcraftgaming** [Mcbamboo/bicubic-shaders-be#28]
Can you fix this issue, it's only on bicubic shader 3.0
**I'm on iOS**.

https://user-images.githubusercontent.com/83649025/129799545-faab3aa3-efbb-44e3-ad37-afd79aca004e.MOV

https://user-images.githubusercontent.com/83649025/129799697-bdb76651-3cda-4578-972f-5b71d0bce943.MOV

https://user-images.githubusercontent.com/83649025/129800599-8ac6806c-22ca-49b2-8f99-0ce2f1c0bf8c.MOV

Please fix it, bicubic shader is the best shader for mcpe

**Comment by bambosan** [comment]
thanks for report,, sorry im slow response
