### ISSUE TITLE
Night Vision not working

### ISSUE THREAD

**Issue by KAWAIIMAKER** [Mcbamboo/bicubic-shaders-be#3]
![Screenshot_20210508-170317_Minecraft](https://user-images.githubusercontent.com/83860593/117531917-e0fbb880-b01f-11eb-923d-4e80f35bb0b0.jpg)

![Screenshot_20210508-170300_Minecraft](https://user-images.githubusercontent.com/83860593/117531878-bad61880-b01f-11eb-9bd2-07176025953f.jpg)

![Screenshot_20210508-170236_Minecraft](https://user-images.githubusercontent.com/83860593/117531924-e953f380-b01f-11eb-88de-98babec180a5.jpg)

![Screenshot_20210508-170251_Minecraft](https://user-images.githubusercontent.com/83860593/117531887-c1fd2680-b01f-11eb-8111-aabaca6cace5.jpg)

**Comment by bambosan** [comment]
thanks for reporting!!
