### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by leaf403** [Mcbamboo/bicubic-shaders-be#32]
The glass is opaque in BSBE 3.1

![Screenshot (166)](https://user-images.githubusercontent.com/108045150/181223561-d320c66f-a965-4b9f-a68d-2d4d42f6f70b.png)

<sup>and btw the plants are not waving on my pc</sup>

**Comment by catwithabat** [comment]
what all are you doing Ahan?

**Comment by bambosan** [comment]
Sorry, the glass is a bug but  the foliage movement  I haven't added  it so
don't worry, I'll fix it quickly
thanks for report
