### ISSUE TITLE
Instructions on how to install

### ISSUE THREAD

**Issue by DriftN2Forty** [Mcbamboo/bicubic-shaders-be#35]
Where do you put the BIN files?  I cannot find any information on how to use this

**Comment by xmb9** [comment]
what platform are you on, android, ios, windows?

**Comment by Onikabuto-san** [comment]
The same question. Installed BSBE-RD-Material-Support.mcpack, where to put the files from BSBE-RD-Materials-Windows-3.1.zip ? My system is windows 11.

**Comment by DriftN2Forty** [comment]
> 

I am on Windows 10.  Game is installed at \AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe

**Comment by SetembroSeth** [comment]
@bambosan how do you install the texture on Android?

**Comment by eastwing27** [comment]
Same question here, the mod seems to be installed but there are no visible changes. I assume we need to copy the bin files - but where to?

**Comment by xmb9** [comment]
The issue is Windows won't allow you to perform any changes on the file, so you must download the Appx, and manually replace the files after extracting it, then repack it.

**Comment by Applebobbbb** [comment]
How to install on iOS MCPE 1.19.51? I have no idea what to do with my materials folder and my support folder.

**Comment by xmb9** [comment]
You'll need to be jailbroken. @Applebobbbb
