### ISSUE TITLE
Not working in 1.19.60+ 

### ISSUE THREAD

**Issue by rad1914** [Mcbamboo/bicubic-shaders-be#36]
Hello,
I've tried to install the Bicubic resources as I always have, and everything went well. the problem is when when entering the game everything is invisible, until you uninstall the application and use the default application, it is not possible to see anything. 
I have attached some photos with the error that I have, with the default application without extra resources other than vanilla, and without making any other modifications. 

![Screenshot_20230220-141759_Minecraft](https://user-images.githubusercontent.com/51271703/220191723-2bc1f38b-8ef3-4c63-8255-09c514ea0b06.png)
![Screenshot_20230220-141739_Minecraft](https://user-images.githubusercontent.com/51271703/220191732-a20b2fa0-ce25-4a76-b30d-76567f1eb934.png)
https://user-images.githubusercontent.com/51271703/220191735-00320381-f60b-4d73-83b3-eaca95288929.mp4

Thank you.

**Comment by RazwanGazi** [comment]
Same here i am on Bedrock/PC version tried on 1.19.60-1.19.70. Still does'nt Work.

**Comment by bambosan** [comment]
it's updated it now
you can try
