### ISSUE TITLE
3.2 is very laggy compared to 3.1

### ISSUE THREAD

**Issue by PiwiiMG** [Mcbamboo/bicubic-shaders-be#37]
I admired your work and was looking forward to the 3.2 update, but could you make a version of 3.1 with compatibility with minecraft 1.19.71? The Bicubic 3.2 version has a lot of lag, with version 3.1 I went to 60fps and with 3.2 I barely reached 20 fps

**Comment by bambosan** [comment]
sorry for that, here I change the entire lighting system and apply 3d
clouds on reflection, maybe this is just and I'm doing optimization for the
next update
