### ISSUE TITLE
The shader isn'rt working

### ISSUE THREAD

**Issue by lol-ivan** [Mcbamboo/bicubic-shaders-be#4]
![Screenshot_20210510-054430_Minecraft](https://user-images.githubusercontent.com/74445509/117589384-4ef4cc80-b153-11eb-8a8b-b3e8194c50a3.jpg)

Textures won't load and the lighting doesn't work

Device: samsung A50 (exynos 9610)
Android ver.: 11

**Comment by bambosan** [comment]
okay,, thanks for report !

**Comment by hadakava** [comment]
same on poco x3 nfc, android 10
