### ISSUE TITLE
Shaders are not working.

### ISSUE THREAD

**Issue by DominoKorean** [Mcbamboo/bicubic-shaders-be#45]
I tried using Bicubic 3.4 in BetterRenderDragon 1.3.3, but nothing seems to be working, and it's just vanilla Minecraft.
https://youtu.be/t8M9Gm44noA

**Comment by bambosan** [comment]
You're just installed version 3.3

**Comment by bambosan** [comment]
https://bambosan.github.io/Bicubic-Shaders-BE/

**Comment by DominoKorean** [comment]
I've already tried it. The result is the same.

**Comment by bambosan** [comment]
What version of MCBE are you using?

**Comment by bambosan** [comment]
Ah sorry its 1.20.1

**Comment by bambosan** [comment]
Maybe you can try remove some of my previous shader

**Comment by DominoKorean** [comment]
It has been resolved.
I tried deleting the resource pack and reloading the mcpack several times, and finally succeeded.
![image](https://github.com/bambosan/Bicubic-Shaders-BE/assets/110039366/0631b8f6-fb9b-40fa-9165-956b619be265)

**Comment by ZephyralGaming** [comment]
i have same issue can u tell me u r discord to solve the problem plz
