### ISSUE TITLE
The world becomes kinda white after opening chat or pause screen. Becomes normal after few seconds

### ISSUE THREAD

**Issue by atashi764** [Mcbamboo/bicubic-shaders-be#5]
Umm what can I do? I don't have enough internet balance to upload a video. But I'll upload soon
![Screenshot_20210511-155820](https://user-images.githubusercontent.com/40156662/117804291-6c23bb00-b279-11eb-9a33-854458337f55.jpg)

Snapdragon 439
Android 10
MC 1.16.221

**Comment by bambosan** [comment]
What happened?

**Comment by atashi764** [comment]
@Mcbamboo it's hard to explain in text. I'll include a video soon.

**Comment by bambosan** [comment]
Ok, I will wait

**Comment by bambosan** [comment]
eh, wait,, looks like you don't need to send a video, I already understand that

**Comment by bambosan** [comment]
everything happened because of rain detection and this is very difficult to fix because the fog value is always different in the setting menus and gameplay
