### ISSUE TITLE
Nether

### ISSUE THREAD

**Issue by zevanq** [Mcbamboo/bicubic-shaders-be#6]
This is The best shader ngl, It also work on my low device, But It's too dark in nether

![Screenshot_2021-05-12-14-17-22-16_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/84066386/117934903-58d22780-b32d-11eb-822e-320a7e770d18.jpg)

@Mcbamboo

**Comment by bambosan** [comment]
lighting for nether and endworld will be added in the next version (wip)

thanks for trying!
