### ISSUE TITLE
Water and floor grain 

### ISSUE THREAD

**Issue by AxelWuff** [Mcbamboo/bicubic-shaders-be#7]
![49E9CF44-0B14-4309-9993-33FFCFBA44E3](https://user-images.githubusercontent.com/84246443/119408227-9c6c5000-bca2-11eb-951b-25319f204a52.jpeg)
![F8B46FFA-AB1A-434D-8BE6-4C8018DE29F4](https://user-images.githubusercontent.com/84246443/119408232-9eceaa00-bca2-11eb-87fe-d064542cb1aa.png)
![0E111638-2D44-41E8-84A8-D99BD2CCB3C2](https://user-images.githubusercontent.com/84246443/119408236-a1310400-bca2-11eb-88b4-5eba00624a1a.png)
![867D20B5-E882-4A2D-820F-7328DFD0EDB6](https://user-images.githubusercontent.com/84246443/119408239-a1c99a80-bca2-11eb-8f75-f3246386faef.png)

Shader version: 3.0.0
Mc version: 2.16.221
Device: iPhone SE 2020 
Software: 14.5.1
Issue: The water and land when far away is super grainy and glitched from a distance and the sides of flowing water are like TV static from a short to long distance. I am unsure why that is happening 

Sorry if I wasn't supposed to report issues here im new to this

**Comment by SteveAlexM** [comment]
yeah, i'm like that too
