### ISSUE TITLE
End Lighting

### ISSUE THREAD

**Issue by AE83-X-I-9** [Mcbamboo/bicubic-shaders-be#8]
The end in my experience is dark I can't see anything. Also please make a low version cause in bsbe v2 I could run it very smooth at the low shaders but now I can't. Anyways awesome shader would love to see it properly working.

**Comment by bambosan** [comment]
I'm working on that and also adding a new lighter setting, if you want to try it you can download it directly from the dev branch

**Comment by bambosan** [comment]
not release
