### ISSUE TITLE
Water texture

### ISSUE THREAD

**Issue by Thariq420** [Mcbamboo/bicubic-shaders-be#9]
![Screenshot_2021-05-21-22-10-25-74_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/84583916/119160447-7d8f7300-ba82-11eb-8f3f-27267801fbbc.jpg)

What's wrong with the water texture? (Sorry for my bad english)

**Comment by bambosan** [comment]
no problem,,, thanks for report
